### ISSUE TITLE
Loader_version

### ISSUE THREAD

**Issue by Yakabuff** [pack-png-mods/alpha-example-mod#1]
Hi,

Where did you find the the loader version. You used the value `3044a80d` but it doesn't appear to be on fabric site linked in the gradle.properties file.  

Would it also be possible to use this template for other versions of minecraft?

Thanks :)

`
# Fabric Properties
	# check these on https://fabricmc.net/use
	minecraft_version=a1.2.2a
	loader_version=3044a80d`

**Comment by Earthcomputer** [comment]
> Where did you find the the loader version

https://github.com/pack-png-mods/alpha-example-mod/blob/master/build.gradle#L51

> Would it also be possible to use this template for other versions of minecraft?

It depends on which other versions you are talking about.

**Comment by Yakabuff** [comment]
>> It depends on which other versions you are talking about.

beta 1.7.3.  Would that be possible?

**Comment by Earthcomputer** [comment]
It might require you to fork my loom fork and fix up the reading of beta 1.7.3 MCP mappings, as I'm not sure it'll be compatible. But other than that, I can't see it not being straightforward.

**Comment by mineLdiver** [comment]
Is this even an issue?

**Comment by Earthcomputer** [comment]
Nope, it was a question, and also outdated by now. There's a beta example mod and a custom fabric loader is no longer needed because the issue it fixed is now fixed upstream.
