### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by calmilamsy** [pack-png-mods/alpha-example-mod#2]
Currently trying to debug a mixin because it isn't applying, but there seems to be no logging happening at all when using `@At(<etc>, args = {"log=true"})`

Unless I am missing something, this is a pretty big issue.

Code snippet:

```java
@Redirect(method = "setBlockIDWithMetadata(IIIII)Z", at = @At(value = "FIELD", target = "Lnet/minecraft/src/Chunk;blocks:[B", args = {"array=set", "log=true"}))
private void setBlockAndMetaHook(byte[] blocks, int access, byte blockID, int var1, int var2, int var3, int var4, int var5) {
    // Some code
}
```

**Comment by Earthcomputer** [comment]
Alpha Minecraft doesn't use log4j, so there's no log4j config hence you're seeing no log4j messages. This is alpha, I don't intend to make this anything more than lightweight. Usually you don't *need* log4j log messages so I didn't add any default config. Supply a log4j config yourself if you want one.

**Comment by mineLdiver** [comment]
> 
> 
> Alpha Minecraft doesn't use log4j, so there's no log4j config hence you're seeing no log4j messages. This is alpha, I don't intend to make this anything more than lightweight. Usually you don't _need_ log4j log messages so I didn't add any default config. Supply a log4j config yourself if you want one.

How would I do this?

**Comment by Earthcomputer** [comment]
That is a good question that I'm afraid I don't know the answer to. Try looking it up.

**Comment by mineLdiver** [comment]
> 
> 
> That is a good question that I'm afraid I don't know the answer to. Try looking it up.

Calmilamsy figured out, this line:
Configurator.setLevel("mixin", org.apache.logging.log4j.Level.TRACE);
onInitialize() enables the config.

**Comment by calmilamsy** [comment]
As above, I've figured it out. Thanks for the help EarthComputer!
